#!/bin/sh
# Bounded, crash-safe physical standby seeding inside a pg-fc guest.
set -eu

for pgbin in /usr/lib/postgresql/*/bin; do
    [ ! -d "$pgbin" ] || PATH="$pgbin:$PATH"
done
export PATH LC_ALL=C
umask 077
WORKSPACE=${PG_FC_WORKSPACE:-/workspace}
PGDATA=${PG_FC_PGDATA:-$WORKSPACE/pgdata}
ROOT_MARKER=${PG_FC_ROOT_MARKER:-/etc/pg-fc-physical-persistent-required}
STATE_DIR="$WORKSPACE/pg-fc-physical"
PLAN="$STATE_DIR/plan.json"
ACTIVE="$STATE_DIR/activated.json"
STATUS="$STATE_DIR/status.json"
LOCK="$STATE_DIR/seed.lock"
COMMAND=${1:-}

say_status() {
    phase=$1 error=${2:-}
    mkdir -p "$STATE_DIR"
    tmp="$STATE_DIR/.status.$$"
    jq -nc --arg phase "$phase" --arg error "$error" \
        '{phase:$phase,error:(if $error == "" then null else $error end)}' >"$tmp"
    chmod 600 "$tmp"; chown postgres:postgres "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$STATUS"
}

fail() {
    say_status failed "$1"; echo "pg-fc-physical: $1" >&2
    [ "$COMMAND" != boot-check ] || exit 20
    exit "${2:-1}"
}

persistent_workspace() {
    [ "${PG_FC_TEST_ALLOW_NONMOUNT:-0}" = 1 ] || mountpoint -q "$WORKSPACE"
}

load_plan() {
    [ -f "$PLAN" ] || return 1
    [ "${PG_FC_TEST_ALLOW_PLAN_OWNER:-0}" = 1 ] || [ "$(stat -c %U "$PLAN")" = postgres ] || fail "plan owner must be postgres"
    [ "${PG_FC_TEST_ALLOW_PLAN_OWNER:-0}" = 1 ] || [ "$(stat -c %a "$PLAN")" = 600 ] || fail "plan mode must be 0600"
    jq -e '. as $plan |
      ($plan|type == "object") and
      ($plan.generation|type=="string" and test("^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")) and
      ($plan.system_identifier|type=="string" and test("^[0-9]+$")) and
      ($plan.pg_major|type=="number" and floor==. and .>=1) and
      ($plan.conninfo|type=="string" and length>0) and
      ($plan.slot|type=="string" and test("^[a-z0-9_]{1,63}$")) and
      ($plan.settings|type=="object") and
      (["max_connections","max_prepared_transactions","max_locks_per_transaction","max_wal_senders","max_worker_processes"] |
       all(. as $k | ($plan.settings[$k]|type=="number" and floor==. and .>=0)))' "$PLAN" >/dev/null \
      || fail "invalid plan"
    generation=$(jq -r .generation "$PLAN")
    system_identifier=$(jq -r .system_identifier "$PLAN")
    pg_major=$(jq -r .pg_major "$PLAN")
    slot=$(jq -r .slot "$PLAN")
}

installed_major() {
    postgres --version | sed -n 's/.* \([0-9][0-9]*\)\..*/\1/p'
}

cluster_system_id() {
    pg_controldata "$1" 2>/dev/null | awk -F: '/Database system identifier/ {gsub(/[[:space:]]/,"",$2); print $2}'
}

verify_cluster() {
    dir=$1
    [ "$(cat "$dir/PG_VERSION" 2>/dev/null)" = "$pg_major" ] || return 1
    [ "$(installed_major)" = "$pg_major" ] || return 1
    [ "$(cluster_system_id "$dir")" = "$system_identifier" ] || return 1
    [ -f "$dir/standby.signal" ] || return 1
    grep -Eq "^[[:space:]]*primary_slot_name[[:space:]]*=[[:space:]]*'${slot}'" "$dir/postgresql.auto.conf" || return 1
    grep -Eq "^[[:space:]]*primary_conninfo[[:space:]]*=" "$dir/postgresql.auto.conf" || return 1
}

write_physical_conf() {
    dir=$1
    conf="$dir/pg-fc-physical.conf"
    {
        echo "# Generated by pg-fc-physical; source recovery minima."
        echo "wal_level = replica"
        echo "hot_standby = on"
        for key in max_connections max_prepared_transactions max_locks_per_transaction max_wal_senders max_worker_processes; do
            printf '%s = %s\n' "$key" "$(jq -r ".settings.$key" "$PLAN")"
        done
    } >"$conf.tmp"
    chown postgres:postgres "$conf.tmp" 2>/dev/null || true; chmod 600 "$conf.tmp"
    mv -f "$conf.tmp" "$conf"
    grep -q "^include = 'pg-fc-physical.conf'" "$dir/postgresql.conf" 2>/dev/null || \
        echo "include = 'pg-fc-physical.conf'" >>"$dir/postgresql.conf"
    # Source ALTER SYSTEM settings otherwise override recovery minima.
    grep -q "^include = 'pg-fc-physical.conf'" "$dir/postgresql.auto.conf" || \
        echo "include = 'pg-fc-physical.conf'" >>"$dir/postgresql.auto.conf"
}

mark_active() {
    tmp="$STATE_DIR/.activated.$$"
    jq -nc --arg generation "$generation" --arg system_identifier "$system_identifier" \
      '{generation:$generation,system_identifier:$system_identifier,verified:true}' >"$tmp"
    chmod 600 "$tmp"; chown postgres:postgres "$tmp" 2>/dev/null || true
    mv -f "$tmp" "$ACTIVE"; sync
}

is_active() {
    [ -f "$ACTIVE" ] &&
      [ "$(jq -r '.verified // false' "$ACTIVE" 2>/dev/null)" = true ] &&
      [ "$(jq -r '.generation // ""' "$ACTIVE" 2>/dev/null)" = "$generation" ] &&
      [ "$(jq -r '.system_identifier // ""' "$ACTIVE" 2>/dev/null)" = "$system_identifier" ] &&
      verify_cluster "$PGDATA"
}

boot_check() {
    if [ ! -f "$PLAN" ]; then
        if [ -e "$ROOT_MARKER" ]; then
            fail "physical marker exists without its durable plan" 20
        fi
        echo normal; exit 0
    fi
    persistent_workspace || fail "physical plan requires persistent workspace" 20
    load_plan
    if is_active; then say_status active; echo active; exit 10; fi
    say_status inhibited "physical activation is not verified"
    echo inhibited; exit 20
}

seed() {
    persistent_workspace || fail "physical seed requires persistent workspace"
    load_plan
    : >"$ROOT_MARKER" 2>/dev/null || fail "cannot install persistent-required marker"
    chmod 600 "$ROOT_MARKER" 2>/dev/null || true
    exec 9>"$LOCK"
    if ! flock -n 9; then echo "seed already running" >&2; exit 75; fi
    sync
    if is_active; then
        if ! gosu postgres pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
            gosu postgres pg_ctl -D "$PGDATA" -w start >"$WORKSPACE/pg-startup.log" 2>&1 || fail "activated standby failed to restart"
        fi
        say_status active; exit 0
    fi
    [ ! -e "$ACTIVE" ] || fail "activated standby identity changed; refusing to reseed its data"

    # A crash after the activation rename is completed by verifying, never by initdb.
    if verify_cluster "$PGDATA"; then
        write_physical_conf "$PGDATA"; mark_active
    else
        scratch="$STATE_DIR/scratch.$generation"
        # A kill between the two activation renames leaves canonical absent.
        # Restore the quarantined disposable cluster before retrying the copy.
        if [ ! -e "$PGDATA" ] && [ -d "$scratch" ]; then mv "$scratch" "$PGDATA"; fi
        if [ -s "$PGDATA/postmaster.pid" ]; then
            say_status stopping_scratch
            if ! gosu postgres pg_ctl -D "$PGDATA" -m fast -w stop >/dev/null 2>&1; then
                gosu postgres pg_ctl -D "$PGDATA" status >/dev/null 2>&1 && fail "scratch postgres did not stop"
                rm -f "$PGDATA/postmaster.pid"
            fi
        fi
        [ ! -s "$PGDATA/postmaster.pid" ] || fail "scratch postgres still appears running"
        stage="$STATE_DIR/staging.$generation"
        rm -rf "$stage"
        mkdir -p "$stage"; chown postgres:postgres "$stage"; chmod 700 "$stage"
        say_status copying
        conninfo=$(jq -r .conninfo "$PLAN")
        export PG_FC_CONNINFO="$conninfo"
        unset conninfo
        service_file="$STATE_DIR/seed.service"
        python3 - "$service_file.tmp" <<'PY'
import ctypes, ctypes.util, os, sys
c = os.environ["PG_FC_CONNINFO"]
if "\n" in c or "\r" in c:
    raise SystemExit("newline in conninfo")
class Option(ctypes.Structure):
    _fields_ = [(k, ctypes.c_char_p) for k in ("keyword", "envvar", "compiled", "val", "label", "dispchar")] + [("dispsize", ctypes.c_int)]
pq = ctypes.CDLL(ctypes.util.find_library("pq"))
pq.PQconninfoParse.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_char_p)]
pq.PQconninfoParse.restype = ctypes.POINTER(Option)
pq.PQconninfoFree.argtypes = [ctypes.POINTER(Option)]
error = ctypes.c_char_p()
options = pq.PQconninfoParse(c.encode(), ctypes.byref(error))
if not options: raise SystemExit("invalid libpq conninfo")
pairs = []
i = 0
while options[i].keyword:
    if options[i].val is not None: pairs.append((options[i].keyword.decode(), options[i].val.decode()))
    i += 1
pq.PQconninfoFree(options)
with open(sys.argv[1], "w") as f:
    f.write("[physical_seed]\n")
    for key, value in pairs:
        if not key.replace("_", "").isalnum() or "\n" in value: raise SystemExit("invalid conninfo key/value")
        f.write(f"{key}={value}\n")
PY
        chown postgres:postgres "$service_file.tmp"; chmod 600 "$service_file.tmp"; mv "$service_file.tmp" "$service_file"
        export PGSERVICEFILE="$service_file"
        gosu postgres pg_basebackup -d service=physical_seed -D "$stage" -R -X stream -S "$slot" --no-password --checkpoint=fast \
          >"$STATE_DIR/basebackup.log" 2>&1 || fail "base backup failed (see basebackup.log)"
        # The seeding service path is not inherited by postgres on a later
        # boot. Persist the original conninfo in auto.conf (0600 PGDATA), with
        # PostgreSQL configuration-string escaping, never on argv or stdout.
        python3 - "$stage/postgresql.auto.conf" <<'PY'
import os, sys
c = os.environ["PG_FC_CONNINFO"].replace("\\", "\\\\").replace("'", "''")
with open(sys.argv[1], "a") as f: f.write("primary_conninfo = '" + c + "'\n")
PY
        unset PG_FC_CONNINFO PGSERVICEFILE
        say_status verifying
        gosu postgres pg_verifybackup "$stage" >"$STATE_DIR/verifybackup.log" 2>&1 || fail "backup manifest verification failed"
        verify_cluster "$stage" || fail "seed identity, version, or recovery configuration mismatch"
        write_physical_conf "$stage"
        sync
        [ "${PG_FC_TEST_FAIL_AT:-}" != after-copy ] || fail "injected failure after copy"
        [ ! -e "$scratch" ] || fail "scratch quarantine already exists"
        mv "$PGDATA" "$scratch" || fail "could not quarantine scratch PGDATA"
        [ "${PG_FC_TEST_FAIL_AT:-}" != after-quarantine ] || fail "injected failure after quarantine"
        if ! mv "$stage" "$PGDATA"; then mv "$scratch" "$PGDATA" 2>/dev/null || true; fail "could not activate standby"; fi
        sync
        verify_cluster "$PGDATA" || fail "activated standby did not verify"
        mark_active
        rm -rf "$scratch"
    fi
    say_status starting
    mkdir -p /var/run/postgresql; chown postgres:postgres /var/run/postgresql
    gosu postgres pg_ctl -D "$PGDATA" -w start >"$WORKSPACE/pg-startup.log" 2>&1 || fail "activated standby failed to start"
    say_status active
}

status_cmd() {
    if [ -f "$STATUS" ]; then jq -c '{phase,error}' "$STATUS"; else echo '{"phase":"normal","error":null}'; fi
}

case "${1:-}" in
    seed) seed ;;
    boot-check) boot_check ;;
    status) status_cmd ;;
    *) echo "usage: pg-fc-physical {seed|boot-check|status}" >&2; exit 64 ;;
esac
